language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t kkereziev/docker-react -f Dockerfile.dev .

script:
  - docker run kkereziev/docker-react npm run test -- --coverage